// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDgOMQq4752f8RvuA8GBytKJEvd4QdmLk',
    appId: '1:267878163827:web:295b3ee3f62e8b7cc81106',
    messagingSenderId: '267878163827',
    projectId: 'proje-e6d93',
    authDomain: 'proje-e6d93.firebaseapp.com',
    storageBucket: 'proje-e6d93.appspot.com',
    measurementId: 'G-CK0JHM32S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRszWH84xfHboqFYW_UQoycQ2uhcOcWsk',
    appId: '1:267878163827:android:4a4b17920eca4443c81106',
    messagingSenderId: '267878163827',
    projectId: 'proje-e6d93',
    storageBucket: 'proje-e6d93.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDgOMQq4752f8RvuA8GBytKJEvd4QdmLk',
    appId: '1:267878163827:web:4b65f367e6e41655c81106',
    messagingSenderId: '267878163827',
    projectId: 'proje-e6d93',
    authDomain: 'proje-e6d93.firebaseapp.com',
    storageBucket: 'proje-e6d93.appspot.com',
    measurementId: 'G-BTLBDY1F3M',
  );
}
